import React, { useState, useEffect } from 'react';
import { 
  Plus, 
  Settings, 
  HelpCircle, 
  Compass, 
  TrendingUp, 
  CheckSquare, 
  Bot, 
  Activity, 
  ArrowRight,
  Briefcase
} from 'lucide-react';

interface TestCase {
  id: string;
  title: string;
  test_prompt: string;
  created_at: string;
}

interface Suggestion {
  id: string;
  test_case_id: string;
  suggestion_text: string;
}

interface AISuggestionsProps {
  userToken: string;
  onNavigateToCreate: () => void;
}

export default function AISuggestions({ userToken, onNavigateToCreate }: AISuggestionsProps) {
  const [testCases, setTestCases] = useState<TestCase[]>([]);
  const [selectedCaseId, setSelectedCaseId] = useState<string>('');
  const [suggestions, setSuggestions] = useState<Suggestion[]>([]);
  const [loadingCases, setLoadingCases] = useState(true);
  const [loadingSuggestions, setLoadingSuggestions] = useState(false);

  const fetchCases = async () => {
    try {
      setLoadingCases(true);
      const res = await fetch('/api/tests', {
        headers: { 'Authorization': `Bearer ${userToken}` }
      });
      const data = await res.json();
      setTestCases(data);
      if (data.length > 0) {
        setSelectedCaseId(data[0].id);
        fetchSuggestions(data[0].id);
      }
    } catch (e) {
      console.error('Failed to load test cases of suggestions:', e);
    } finally {
      setLoadingCases(false);
    }
  };

  const fetchSuggestions = async (caseId: string) => {
    try {
      setLoadingSuggestions(true);
      const res = await fetch(`/api/ai/suggestions/${caseId}`);
      const data = await res.json();
      setSuggestions(data);
    } catch (err) {
      console.error('Failed to retrieve suggestions', err);
    } finally {
      setLoadingSuggestions(false);
    }
  };

  useEffect(() => {
    fetchCases();
  }, [userToken]);

  const handleSelectCase = (id: string) => {
    setSelectedCaseId(id);
    fetchSuggestions(id);
  };

  const activeCase = testCases.find(tc => tc.id === selectedCaseId);

  return (
    <div id="ai-suggestions-view" className="p-8 pb-16 space-y-8 text-[#F8FAFC]">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">AI Test Coverage Recommendations</h1>
        <p className="text-sm text-slate-400 mt-1">Review AI recommendations and optimization checklists generated by Gemini to improve test depth and accuracy.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-8">
        
        {/* Left Side: List of Scenarios (2 cols) */}
        <div className="lg:col-span-2 bg-[#1E293B] border border-slate-800 rounded-xl p-5 shadow-sm space-y-4">
          <h3 className="text-sm font-bold tracking-tight uppercase text-slate-400 pb-2 border-b border-slate-850 select-none">Select Scenario Scope</h3>
          
          {loadingCases ? (
            <div className="py-12 text-center text-slate-500 font-medium">
              <span className="animate-pulse">Loading scenarios list...</span>
            </div>
          ) : testCases.length === 0 ? (
            <div className="py-12 text-center text-slate-500 rounded-lg bg-[#0F172A]/40 border border-dashed border-slate-800 p-4">
              <Compass className="w-8 h-8 text-indigo-400/40 mx-auto mb-2" />
              <p className="text-sm font-bold text-slate-350">No test cases created yet</p>
              <p className="text-xs text-slate-500 mt-1 max-w-xs mx-auto">Create a test case on the test page to receive automated coverage suggestions.</p>
              <button
                onClick={onNavigateToCreate}
                className="mt-3.5 px-3 py-1.5 bg-indigo-600/20 text-indigo-400 text-xs font-semibold hover:bg-[#6366F1]/30 rounded transition-colors cursor-pointer"
              >
                Incorporate scenario
              </button>
            </div>
          ) : (
            <div className="space-y-2 select-none">
              {testCases.map((tc) => (
                <div
                  key={tc.id}
                  onClick={() => handleSelectCase(tc.id)}
                  className={`p-3.5 rounded-lg border cursor-pointer transition-colors duration-150 ${
                    selectedCaseId === tc.id 
                      ? 'bg-indigo-600/10 border-indigo-500/50 text-white' 
                      : 'bg-[#0F172A] border-slate-850 text-slate-400 hover:border-slate-800 hover:text-slate-200'
                  }`}
                >
                  <p className="text-xs font-bold leading-normal">{tc.title}</p>
                  <p className="text-[10px] text-slate-500 font-mono mt-1.5 truncate">prompt: {tc.test_prompt}</p>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Right Side: Suggestions List details (3 cols) */}
        <div className="lg:col-span-3 bg-[#1E293B] border border-slate-800 rounded-xl p-6 shadow-sm flex flex-col justify-between">
          <div className="space-y-5">
            <div className="flex items-center gap-2 pb-3 border-b border-slate-850">
              <Bot className="w-5 h-5 text-indigo-400 shrink-0" />
              <h3 className="text-sm font-bold tracking-tight uppercase text-slate-400">Gemini Optimization Audit</h3>
            </div>

            {loadingSuggestions ? (
              <div className="py-20 text-center text-slate-500 font-medium font-sans">
                <span className="animate-pulse">Gemini is inspecting active scenario...</span>
              </div>
            ) : !selectedCaseId ? (
              <div className="py-20 text-center text-slate-500 font-sans">
                <Compass className="w-10 h-10 text-slate-650 mx-auto mb-3" />
                <p className="text-xs font-bold">Awaiting test scenario choice</p>
              </div>
            ) : (
              <div className="space-y-5">
                {/* Active user prompt */}
                <div className="p-4 bg-[#0F172A] border border-slate-850 rounded-lg">
                  <p className="text-[10px] font-bold text-slate-500 mb-1">ORIGINAL SCENARIO STATEMENT</p>
                  <p className="text-xs font-mono text-[#CBD5E1] leading-relaxed select-all">"{activeCase?.test_prompt}"</p>
                </div>

                <div className="space-y-4">
                  <p className="text-xs font-bold uppercase tracking-wider text-slate-400">AI Suggested Assertions &amp; Checks</p>
                  
                  {suggestions.length === 0 ? (
                    <div className="p-3 bg-[#0F172A]/50 border border-slate-850 rounded text-slate-500 text-xs">
                      No static coverage suggestions mapped.
                    </div>
                  ) : (
                    <div className="space-y-3">
                      {suggestions.map((sug, idx) => (
                        <div 
                          key={sug.id || idx}
                          className="flex items-start gap-3 p-3.5 rounded-lg bg-indigo-500/[0.03] border border-indigo-500/10"
                        >
                          <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center font-bold text-xs font-mono shrink-0 select-none border border-slate-700/80">
                            {idx + 1}
                          </span>
                          <div className="text-xs text-slate-200 leading-relaxed font-sans select-all">
                            {sug.suggestion_text}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>

          {selectedCaseId && !loadingSuggestions && (
            <div className="pt-6 border-t border-slate-850 mt-8 shrink-0">
              <button 
                onClick={onNavigateToCreate}
                className="w-full bg-[#6366F1] hover:bg-indigo-600 text-white font-bold text-sm py-2.5 rounded-lg flex items-center justify-center gap-2 cursor-pointer shadow-lg hover:shadow-indigo-500/10 transition-colors"
                title="Create a test employing those assertions"
              >
                <span>Incorporate Recommendations In Wizard</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          )}

        </div>

      </div>

    </div>
  );
}
